name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: yarn install
      
      - name: Run ESLint
        run: yarn lint

      - name: Build project
        run: yarn build
        env:
          VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}
          VITE_AUTH0_CALLBACK_URL: ${{ vars.VITE_AUTH0_CALLBACK_URL }}
          VITE_BACKEND_HOST: ${{ vars.VITE_BACKEND_HOST }}
          VITE_BACKEND_PROTOCOL: ${{ vars.VITE_BACKEND_PROTOCOL }}
          VITE_BACKEND_API_KEY: ${{ secrets.VITE_BACKEND_API_KEY }}