name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: yarn install
      
      - name: Run ESLint
        run: yarn lint

      - name: Build project
        run: yarn build
      
      - name: Serve the build
        run: |
          yarn global add serve
          serve -s dist &
          sleep 5
      
      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: 'http://localhost:5000'
          output_path: './lighthouse-results'
          uploadArtifacts: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync S3 bucket
        run: aws s3 sync dist/ s3://frontend-cloud-storage --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"